### ISSUE TITLE
Can't build Werecat

### ISSUE THREAD

**Issue by ericbeland** [whicken/Werecat#10]
This project looks really nice. So far I can't get it to build. I'm trying to use it in a gradle project, and I've been using jitpack.io in an attempt to build from this repo. 

https://jitpack.io/com/github/whicken/Werecat/6a4935cd57/build.log

https://jitpack.io/#whicken/Werecat

Any thoughts?

**Comment by cepeza** [comment]
Could it be java 1.8 issue? Try recompiling with java 1.6.

Sergey

**Comment by whicken** [comment]
I'm guessing the problem is that Antlr isn't running. If you do this manually first (see the README file in the parser folder), it should work

**Comment by ericbeland** [comment]
Sorry, should have checked in to close the loop. It was an Antlr problem.  Thanks!
